### PR TITLE
Fix documentation report's percent calculation.

### LINKED ISSUE #672: new report: documentation percent is wrong
`1%` instead of `100%` (missing multiplication with 100)

### PR DESCRIPTION
**Pull request by isoos**
Fixes #672

### CODE REVIEW

**Comment by isoos** [comment]
PTAL.

File: lib/src/dartdoc_analyzer.dart [hunk 1]
```diff
@@ -57,19 +59,31 @@ ReportSection documentationCoverageSection({
 
   return ReportSection(
     title: documentationSectionTitle,
-    grantedPoints: accepted ? maxPoints : 0,
+    grantedPoints: grantedPoints,
     maxPoints: maxPoints,
-    summary: summary.toString(),
+    summary: renderSimpleSectionSummary(
+      title: '20% or more of the public api has dartdoc.',
```
Comment (mit-mit) [inline lib/src/dartdoc_analyzer.dart:65]: consider s/dartdoc/dartdoc comments/?
