### PR TITLE
Better handling of JSON parsing issues in pub outdated.

### LINKED ISSUE #949: Handle failing "dart pub outdated" failing non-zero
When `dart pub outdated` we should not try to parse: `"It looks like pub.dartlang.org is having some trouble."`.
Instead when we get exit code non-zero we should probably not try to parse the output.
```
Error: FormatException: Unexpected character (at character 1) It looks like pub.dartlang.org is having some trouble. ^
at _ChunkedJsonParser.fail (native)
at _ChunkedJsonParser.parseNumber (native)
at _ChunkedJsonParser.parse (native)
at _parseJson (native)
at JsonDecoder.convert (native)
at JsonCodec.decode (native)
at ToolEnvironment.runPubOutdated (package:pana/src/sdk_env.dart:364)
at StackZoneSpecification._registerUnaryCallback.<fn> (unknown location)
```

### PR DESCRIPTION
**Pull request by isoos**
- Fixes #949.
- also updated flutter version processing to use the same method

### CODE REVIEW

**Review by jonasfj — APPROVED** [review]

File: lib/src/sdk_env.dart [hunk 1]
```diff
@@ -297,15 +297,17 @@ class ToolEnvironment {
   Future<Map<String, dynamic>> getFlutterVersion() async {
     final result = _handleProcessErrors(
         await runProc([..._flutterCmd, '--version', '--machine']));
-    var content = result.asJoinedOutput;
     final waitingForString = 'Waiting for another flutter';
```
Comment (jonasfj) [inline lib/src/sdk_env.dart:300]: Can't we avoid this if we use `FLUTTER_ROOT=/path/to/flutter dart pub outdated` instead?

Comment (isoos) [reply lib/src/sdk_env.dart:300]: I think this happened sporadically in CI, and while we've changed the flutter setup since, we've always had `FLUTTER_ROOT` set.

Comment (jonasfj) [reply lib/src/sdk_env.dart:300]: My point is: I don't think `dart pub outdated` will ever print this line. But it's possible that `flutter pub outdated` will, so there is no need for this special case if we use `dart pub outdated` with `FLUTTER_ROOT` instead.

Comment (isoos) [reply lib/src/sdk_env.dart:300]: Yeah, we've always run `dart pub outdated` (there was a PR to change that, but got reverted), however, this is `flutter --version --machine`, which did write this on the output, on CI. Let's keep it for a bit, and maybe do a more systemic review of the code later: we should be able to identify similar patterns in multiple places, which may have become obsolete over time.
