### PR TITLE
Suppress more log when the pub upgrade error could be git-related.

### LINKED ISSUE #476: warning -> info, for "pub get" messages for packages with git dependencies
We don't want to see warnings in the logs that some git dependency isn't available anymore, or doesn't contain valid content anymore.

If there is git dependencies, we just say that "pub get" failed, instead of writing any logs or warnings.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #476

### CODE REVIEW

File: lib/src/package_analyzer.dart [hunk 1]
```diff
@@ -212,8 +212,10 @@ class PackageAnalyzer {
         message = LineSplitter.split(upgrade.stderr as String).first;
       }
 
-      final isUserProblem = message.contains('version solving failed') ||
-          message.contains('Git error.');
+      final isUserProblem = pubspec.hasGitDependency ||
+          message.contains('version solving failed') ||
+          message.contains('Git error.') ||
+          message.contains('Could not find a file named "pubspec.yaml" in');
```
Comment (jonasfj) [inline lib/src/package_analyzer.dart]: The last one could happen if a nested package or something weird didn't contain a `pubspec.yaml`?
Hmm.. I guess it's a user problem that you depended on said package then...

Comment (jonasfj) [reply lib/src/package_analyzer.dart]: Least leave a comment arguing why these error messages are ignored...

Comment (isoos) [reply lib/src/package_analyzer.dart]: Removing the last one as it should be covered with the git ones.
