### PR TITLE
Fix: delete local temporary pedantic_analyis_options_[timestamp].g.yaml.

### LINKED ISSUE #522: Unnecessary additional *.g.yaml file isn't deleted from analyzed package.
Why file `pedantic_analizys_option_[digits].g.yaml` doesn't autodelete after analyzing package? I am using a full list of [linter options](https://dart-lang.github.io/linter/lints/options/options.html). But in the created file part of these are just duplicated. 
Pana version 0.12.14.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #522.

### CODE REVIEW

File: lib/src/sdk_env.dart [hunk 1]
```diff
@@ -179,6 +179,7 @@ class ToolEnvironment {
       return output;
     } finally {
       await customOptionsFile.delete();
+      await pedanticOptionsFile.delete();
```
Comment (jonasfj) [inline lib/src/sdk_env.dart]: How about refactoring this as:
```dart
await withTempFile(name, content, () async {
  ...
});
```

Then have `withTempFile` write the file and delete it after the function given as last parameter is finished...
That way you can easily have both files in their own `finally {` block... which ensures that the second file is deleted, even if the first file wasn't deleted...

side note: couldn't we put these files in `/tmp/`, ideally using https://api.dartlang.org/stable/2.2.0/dart-io/Directory/systemTemp.html

Comment (jonasfj) [reply lib/src/sdk_env.dart]: Just a suggestion :)

Comment (isoos) [reply lib/src/sdk_env.dart]: I've added a `TODO` to address this later.
