### PR TITLE
Do not fail markdown checks on malformed UTF-8 files.

### LINKED ISSUE #756: Error: FileSystemException: Failed to decode data using encoding 'utf-8', path = .../README.md'
from logs
```
Error: FileSystemException: Failed to decode data using encoding 'utf-8', path = '/tmp/pana_JOIUJS/README.md'
at _File.readAsString (native)
at scanMarkdownFileContent (package:pana/src/markdown_content.dart:49)
at analyzeMarkdownFile (package:pana/src/markdown_content.dart:57)
at detectMaintenance (package:pana/src/maintenance.dart:424)
at PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:407)
at PackageAnalyzer.inspectPackage.<fn>.<fn> (package_analyzer.dart:86)
at PackageAnalyzer.inspectPackage.<fn>.<fn> (unknown location)
at withTempDir (package:pana/src/download_utils.dart:245)
at PackageAnalyzer.inspectPackage.<fn> (package_analyzer.dart:83)
at _rootRun (native)
at _CustomZone.run (native)
at _runZoned (native)
at runZoned (native)
at withLogger (package:pana/src/logging.dart:13)
at PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:81)
at AnalyzerJobProcessor.process.analyze (pana_runner.dart:78)
at AnalyzerJobProcessor.process.analyze (unknown location)
at AnalyzerJobProcessor.process (package:pub_dev/analyzer/pana_runner.dart:104)
at JobProcessor.run (package:pub_dev/job/job.dart:69)
at JobMaintenance.run (package:pub_dev/job/job.dart:119)
at _workerMain.<fn> (analyzer.dart:96)
at StackZoneSpecification._registerUnaryCallback.<fn>.<fn> (stack_zone_specification.dart:129)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerUnaryCallback.<fn> (stack_zone_specification.dart:129)
at _rootRunUnary (native)
at _CustomZone.runUnary (native)
at _FutureListener.handleValue (native)
at Future._propagateToListeners.handleValueCallback (native)
at Future._propagateToListeners (native)
at Future._completeWithValue (native)
at _AsyncAwaitCompleter.complete (native)
at _completeOnAsyncReturn (native)
at PopularityStorage.init (unknown location)
at StackZoneSpecification._registerUnaryCallback.<fn>.<fn> (stack_zone_specification.dart:129)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerUnaryCallback.<fn> (stack_zone_specification.dart:129)
at _rootRunUnary (native)
at _CustomZone.runUnary (native)
at _FutureListener.handleValue (native)
at Future._propagateToListeners.handleValueCallback (native)
at Future._propagateToListeners (native)
at Future._completeWithValue (native)
at _AsyncAwaitCompleter.complete (native)
at _completeOnAsyncReturn (native)
at PopularityStorage.fetch (unknown location)
at StackZoneSpecification._registerUnaryCallback.<fn>.<fn> (stack_zone_specification.dart:129)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerUnaryCallback.<fn> (stack_zone_specification.dart:129)
at _rootRunUnary (native)
at _CustomZone.runUnary (native)
at _FutureListener.handleValue (native)
at Future._propagateToListeners.handleValueCallback (native)
at Future._propagateToListeners (native)
at Future._complete (native)
at Stream.single.<fn> (native)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerCallback.<fn> (stack_zone_specification.dart:119)
at _rootRun (native)
at _CustomZone.run (native)
at _CustomZone.runGuarded (native)
at _BufferingStreamSubscription._sendDone.sendDone (native)
at _BufferingStreamSubscription._sendDone (native)
at _BufferingStreamSubscription._close (native)
at _SinkTransformerStreamSubscription._close (native)
at _EventSinkWrapper.close (native)
at _JsonStringDecoderSink.close (native)
at _ConverterStreamEventSink.close (native)
at _SinkTransformerStreamSubscription._handleDone (native)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerCallback.<fn> (stack_zone_specification.dart:119)
at _rootRun (native)
at _CustomZone.run (native)
at _CustomZone.runGuarded (native)
at _BufferingStreamSubscription._sendDone.sendDone (native)
at _BufferingStreamSubscription._sendDone (native)
at _BufferingStreamSubscription._close (native)
at _SinkTransformerStreamSubscription._close (native)
at _EventSinkWrapper.close (native)
at _StringAdapterSink.close (native)
at _Utf8ConversionSink.close (native)
at _ConverterStreamEventSink.close (native)
at _SinkTransformerStreamSubscription._handleDone (native)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerCallback.<fn> (stack_zone_specification.dart:119)
at _rootRun (native)
at _CustomZone.run (native)
at _CustomZone.runGuarded (native)
at _BufferingStreamSubscription._sendDone.sendDone (native)
at _BufferingStreamSubscription._sendDone (native)
at _BufferingStreamSubscription._close (native)
at _SinkTransformerStreamSubscription._close (native)
at _EventSinkWrapper.close (native)
at _ByteAdapterSink.close (native)
at _FilterSink.close (native)
at _ConverterStreamEventSink.close (native)
at _SinkTransformerStreamSubscription._handleDone (native)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerCallback.<fn> (stack_zone_specification.dart:119)
at _rootRun (native)
at _CustomZone.run (native)
at _CustomZone.runGuarded (native)
at _BufferingStreamSubscription._sendDone.sendDone (native)
at _BufferingStreamSubscription._sendDone (native)
at _DelayedDone.perform (native)
at _StreamImplEvents.handleNext (native)
at _PendingEvents.schedule.<fn> (native)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerCallback.<fn> (stack_zone_specification.dart:119)
at _rootRun (native)
at _CustomZone.run (native)
at _CustomZone.runGuarded (native)
at _CustomZone.bindCallbackGuarded.<fn> (native)
at StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
at StackZoneSpecification._registerCallback.<fn> (stack_zone_specification.dart:119)
at _rootRun (native)
at _CustomZone.run (native)
at _CustomZone.runGuarded (native)
at _CustomZone.bindCallbackGuarded.<fn> (native)
at _microtaskLoop (native)
at _startMicrotaskLoop (native)
at _runPendingImmediateCallback (native)
at _Timer._runTimers (native)
at _Timer._handleMessage (native)
at _RawReceivePortImpl._handleMessage (native)
```

### PR DESCRIPTION
**Pull request by isoos**
Fixes #756.

### CODE REVIEW

File: lib/src/markdown_content.dart [hunk 1]
```diff
@@ -52,7 +60,8 @@ List<T> _unique<T>(Iterable<T> l) => l.toSet().toList();
 
 /// Scans a markdown file and extracts its content.
 Future<ExctractedMarkdownContent> scanMarkdownFileContent(File file) async {
-  final text = await file.readAsString();
+  final bytes = await file.readAsBytes();
+  final text = utf8.decode(bytes, allowMalformed: true);
```
Comment (isoos) [inline lib/src/markdown_content.dart:64]: The 100% correct code would first try to decode it without `allowMalformed`, and if that fails, set the flag. However, I don't think that too many valid documents have the replacement character as part of their content.

Comment (jonasfj) [inline lib/src/markdown_content.dart:64]: A better way to do this is to do:
```dart
try {
  text = utf8.decode(bytes, allowMalformed: false);
} on FormatException {
  text = utf8.decode(bytes, allowMalformed: true);
  isMalformedUtf8 = true;
}
```

That way we're not grepping for `_replacementUtf8Char` which the original markdown file could contain... Imagine a README file explaining how UTF8 decoding works :D

Comment (jonasfj) [reply lib/src/markdown_content.dart:64]: But isn't it cheap to do the right thing?

Comment (isoos) [reply lib/src/markdown_content.dart]: Thinking about it: assuming that most files are well-formed, it may be cheaper to do a second pass for malformed ones than always doing a string.contains().

Comment (isoos) [reply lib/src/markdown_content.dart]: Done. PTAL.
